version: "3.8"

volumes:
  mysql57:
    name: mysql57

services:
  server:
    image: "nginx:stable-alpine"
    platform: linux/x86_64
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  artisan:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
  composer:
    image: composer:latest
    working_dir: /var/www/html
    entrypoint: ["composer", "--ignore-platform-reqs"]
    volumes:
      - ./src:/var/www/html